import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" mx-auto max-w-7xl gap-4 px-2 md:px-4">
        <nav className="flex row justify-between py-4 border-b">
          <span>LOGO</span>
          <span>
            <ul className="flex row gap-4 cursor-pointer">
              <li>Tredning</li>
              <li>Deals</li>
              <li>submit</li>
            </ul>
          </span>
        </nav>

        <div className="flex flex-col justify-center gap-4 mt-6 items-center">
          <div className="flex flex-col gap-1 items-center">
            <div className="text-2xl font-semibold">
              Find Ai Tools of Tomorrow
            </div>
            <div className="text-sm">Worlds Largest Directory of Ai Tools</div>
          </div>
          <form class="text-gray-600 shadow-md w-full sm:w-3/4 rounded-full border-2 sm:border-2 border-rose-600 flex justify-around items-center px-2">
            <input
              type="text"
              name="url"
              title="Please enter correct tiktok url"
              placeholder="type AI tool name..."
              className="w-full h-12 px-2 m:h-14 rounded-full text-sm font-light focus:outline-none text-black placeholder:text-slate-600 placeholder:font-light"
              value=""
            />
            <span class="flex items-center">
              <button
                type="submit"
                class="px-4 bg-rose-600 w-min flex justify-center h-8 m:h-10 items-center rounded-full text-white"
              >
                <span class="mr-1">Search</span>
              </button>
            </span>
          </form>
        </div>

        <div className="overflow-x-scroll h-12 flex mt-6">
          <div className="flex justify-start items-center gap-2 w-full">
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Chat
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Copywriting
              </div>
            </div>
            <div>
              <div className="bg-red-600  w-max rounded-full text-white text-xs p-2 cursor-pointer">
                Image Creation
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Content AI
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Video AI
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Audio Generation
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Design
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Writing Assistant
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Code Assistant
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Avatar Generation
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Project Management
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Marketing
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                News
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Search Engine
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Productivity
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Legal
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Education
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Resume
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Noise Cancellation
              </div>
            </div>
            <div>
              <div className="bg-red-600 w-max rounded-full text-white text-xs p-2 px-4 cursor-pointer">
                Model Generation
              </div>
            </div>
          </div>
        </div>

        <div className="flex mt-6 flex-wrap">
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
          <div className="w-full sdm:w-1/2 l:w-1/3">
            <div className="border m-1 p-2 rounded-sm">
              <div>Career Ai</div>
              <div>
                <div>Career Ai</div>
                <div>
                  Ai career suggtion tool for students & working profecianls{" "}
                </div>
                <div>
                  EmailMagic is the AI assistant that helps you write emails 10x
                  faster. Let it be Your Digital Twin. It Writes Emails Just
                  Like You!...
                </div>
                <div>
                  <span>FREE</span>
                  <span>{`-->`}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
