import Cards from "@/components/Cards";
import Catg from "@/components/Catg";
import Hero from "@/components/Hero";
import Nav from "@/components/Nav";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AEM start</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" mx-auto max-w-7xl gap-4 px-6 md:px-6">
        <Nav />
        <Hero />
        {/* <Catg /> */}
        <Cards />
      </main>
    </>
  );
}
